apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: {{ .Values.database.volume.storageClassName }} 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
